name: reason_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

dependencies:
  cupertino_icons: ^1.0.2
  device_info: ^2.0.2
  flutter:
    sdk: flutter
  flutter_local_notifications:
  flutter_native_timezone: ^2.0.0
  http: ^0.13.4
  image: ^3.0.8
  path_provider: ^2.0.0
  rxdart: ^0.27.2
  shared_preferences: ^2.0.1

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

environment:
  sdk: '>=2.12.0-0 <3.0.0'
  flutter: '>=1.26.0-0' # allows for using integration_test from SDK
